title: ReactiveComponent
description: Reactive server-rendered components for Rails via ActionCable
theme: just-the-docs

url: "https://lluzak.github.io"
baseurl: "/reactive_component"

aux_links:
  "GitHub":
    - "https://github.com/lluzak/reactive_component"

nav_sort: case_insensitive
search_enabled: true

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
